// // Copyright 2023 The Flutter Authors. All rights reserved.
// // Use of this source code is governed by a BSD-style license that can be
// // found in the LICENSE file.
// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsSnappyiOS(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsSnappyiOS(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsSnappyiOS(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashSnappyiOS(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashSnappyiOS(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashSnappyiOS(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct SnappyData: Hashable {
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SnappyData? {
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[0])

    return SnappyData(
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      data
    ]
  }
  static func == (lhs: SnappyData, rhs: SnappyData) -> Bool {
    return deepEqualsSnappyiOS(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSnappyiOS(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SnappyResponse: Hashable {
  var success: Bool? = nil
  var message: String? = nil
  var sd: SnappyData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SnappyResponse? {
    let success: Bool? = nilOrValue(pigeonVar_list[0])
    let message: String? = nilOrValue(pigeonVar_list[1])
    let sd: SnappyData? = nilOrValue(pigeonVar_list[2])

    return SnappyResponse(
      success: success,
      message: message,
      sd: sd
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      message,
      sd,
    ]
  }
  static func == (lhs: SnappyResponse, rhs: SnappyResponse) -> Bool {
    return deepEqualsSnappyiOS(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashSnappyiOS(value: toList(), hasher: &hasher)
  }
}

private class SnappyiOSPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SnappyData.fromList(self.readValue() as! [Any?])
    case 130:
      return SnappyResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SnappyiOSPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SnappyData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SnappyResponse {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SnappyiOSPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SnappyiOSPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SnappyiOSPigeonCodecWriter(data: data)
  }
}

class SnappyiOSPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SnappyiOSPigeonCodec(readerWriter: SnappyiOSPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SnappyApi {
  func getMaxCompressedLength() throws -> SnappyData
  func compress(data: SnappyData) throws -> SnappyResponse
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SnappyApiSetup {
  static var codec: FlutterStandardMessageCodec { SnappyiOSPigeonCodec.shared }
  /// Sets up an instance of `SnappyApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SnappyApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMaxCompressedLengthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.preview_play.SnappyApi.getMaxCompressedLength\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMaxCompressedLengthChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMaxCompressedLength()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMaxCompressedLengthChannel.setMessageHandler(nil)
    }
    let compressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.preview_play.SnappyApi.compress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! SnappyData
        do {
          let result = try api.compress(data: dataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      compressChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SnappyNativeCallbackApiProtocol {
  func onUncompress(data dataArg: SnappyData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SnappyNativeCallbackApi: SnappyNativeCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SnappyiOSPigeonCodec {
    return SnappyiOSPigeonCodec.shared
  }
  func onUncompress(data dataArg: SnappyData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.preview_play.SnappyNativeCallbackApi.onUncompress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
